apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-center
  labels:
    app: auth-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-center
  template:
    metadata:
      labels:
        app: auth-center
    spec:
      nodeSelector:
        workload-type: backend-apps
      containers:
        - name: auth-center
          image: auth-center:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
