server:
  port: 8081

# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.blm.common.entity

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


# OpenAPI配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    com.blm: debug
    com.blm.common.feign: debug
    # 启用 Feign 客户端的日志
    org.springframework.cloud.openfeign: debug
    feign: debug
    root: warn

feign:
  client:
    config:
      default:
        # 启用详细日志
        loggerLevel: full
        # 连接超时时间（毫秒）
        connectTimeout: 10000
        # 读取超时时间（毫秒）
        readTimeout: 60000

test:
  dev: local