server:
  port: 8086


# Eureka配置 - K8S环境
eureka:
  instance:
    hostname: admin-service
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
