server:
  port: 8082


# JWT配置
jwt:
  secret: blm-secret-key-for-jwt-token-generation-2025_k8s

# Eureka配置 - K8S环境
eureka:
  instance:
    hostname: auth-center
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
